# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfdb0c642ceb393af65cf4175852c2a72e8a2fceb1c851ec4e8e891bb608333d342da1414ca6fb1037a219bb531f41f1b729b1905f235ce5d7c2329378403eb5

test:
  secret_key_base: dc49367abc16c05b0fc23ea930819d10c7baddda4c7fec7034cdc82d8712e78c37229afc96edc55fd9a1a6feb221377b4ddce33697982f2079abbd61c8ef200e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
